laravel/app/Http/routes.php
<?php

use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Route;

Route::group(['middleware' => ['web']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('sobre', 'SobreController@index')->name('sobre');
    Route::get('projetos/antes-e-depois', 'ProjetosController@indexAntesDepois')->name('projetos.antes-depois');
    Route::get('projetos/antes-e-depois/{projeto}', 'ProjetosController@showAntesDepois')->name('projetos.antes-depois.show');
    Route::get('projetos', 'ProjetosController@index')->name('projetos');
    Route::get('projetos/{projeto}', 'ProjetosController@showImagens')->name('projetos.show');
    Route::get('projetos/categoria/{categoria}', 'ProjetosController@showCategoria')->name('projetos.categoria');
    Route::get('projetos/{categoria}/{projeto}', 'ProjetosController@showCategoriaImagens')->name('projetos.categoria.show');
    Route::get('midia', 'MidiaController@index')->name('midia');
    Route::get('contato', 'ContatoController@index')->name('contato');
    Route::post('contato', 'ContatoController@post')->name('contato.post');
    Route::get('politica-de-privacidade', 'PoliticaDePrivacidadeController@index')->name('politica-de-privacidade');
    Route::post('aceite-de-cookies', 'HomeController@postCookies')->name('aceite-de-cookies.post');

    // Painel
    Route::group([
        'prefix'     => 'painel',
        'namespace'  => 'Painel',
        'middleware' => ['auth']
    ], function () {
        Route::get('/', 'PainelController@index')->name('painel');
        Route::post('ckeditor-upload', 'PainelController@imageUpload');
        Route::post('order', 'PainelController@order');
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
        Route::resource('banners', 'BannersController');
        Route::resource('sobre', 'SobreController', ['only' => ['index', 'update']]);
        Route::resource('projetos', 'ProjetosController', ['except' => 'show']);
        Route::get('projetos/{projeto}/imagens/clear', [
            'as'   => 'painel.projetos.imagens.clear',
            'uses' => 'ProjetosImagensController@clear'
        ]);
        Route::delete('projetos/{projeto}/excluir-imagens/{imagens}', 'ProjetosImagensController@destroyImgs')->name('painel.projetos.excluir-imagens');
        Route::post('projetos/{projeto}/imagens/{imagem}/descricao', 'ProjetosImagensController@updateDescricao')->name('painel.projetos.imagens.descricao');
        Route::resource('projetos.imagens', 'ProjetosImagensController', ['parameters' => ['imagens' => 'projetos_imagens']]);
        Route::resource('projetos-antes-depois', 'ProjetosAntesDepoisController', ['except' => 'show']);
        Route::resource('projetos-antes-depois.imagens', 'ProjetosAntesDepoisImagensController');
        Route::resource('midias', 'MidiasController');
        Route::resource('midias.galeria', 'MidiasGaleriasController');
        Route::get('midias/{galeria}/imagens/clear', [
            'as'   => 'painel.midias.galeria.imagens.clear',
            'uses' => 'MidiasGaleriasImagensController@clear'
        ]);
        Route::resource('midias.galeria.imagens', 'MidiasGaleriasImagensController', ['parameters' => ['imagens' => 'midias_galerias_imagens']]);
        Route::resource('midias.link', 'MidiasLinksController');
        Route::resource('midias.video', 'MidiasVideosController');
        Route::get('contato/recebidos/{recebidos}/toggle', ['as' => 'painel.contato.recebidos.toggle', 'uses' => 'ContatosRecebidosController@toggle']);
        Route::resource('contato/recebidos', 'ContatosRecebidosController');
        Route::resource('contato', 'ContatoController');
        Route::resource('politica-de-privacidade', 'PoliticaDePrivacidadeController', ['only' => ['index', 'update']]);
        Route::get('aceite-de-cookies', 'AceiteDeCookiesController@index')->name('painel.aceite-de-cookies');
        Route::resource('configuracoes', 'ConfiguracoesController', ['only' => ['index', 'update']]);
        Route::resource('usuarios', 'UsuariosController');

        // Limpar caches
        Route::get('clear-cache', function() {
            $exitCode = Artisan::call('config:clear');
            $exitCode = Artisan::call('cache:clear');
            $exitCode = Artisan::call('route:clear');
            $exitCode = Artisan::call('view:clear');
            $exitCode = Artisan::call('config:cache');

            return 'DONE';
        });
    });

    // Auth
    Route::group([
        'prefix'    => 'painel',
        'namespace' => 'Auth'
    ], function () {
        Route::get('login', 'AuthController@showLoginForm')->name('auth');
        Route::post('login', 'AuthController@login')->name('login');
        Route::get('logout', 'AuthController@logout')->name('logout');
        Route::get('esqueci-minha-senha', 'PasswordController@sendEmail')->name('esqueci-minha-senha');
        Route::post('esqueci-minha-senha', 'PasswordController@sendResetLinkEmail')->name('esqueci-minha-senha.post');
        Route::get('reset/{token}', 'PasswordController@showResetForm')->name('password-reset');
        Route::post('reset', 'PasswordController@reset')->name('password-reset.post');
    });
});

laravel/app/Http/Controllers/Painel/AceiteDeCookiesController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Models\AceiteDeCookies;

class AceiteDeCookiesController extends Controller
{
    public function index()
    {
        $registros = AceiteDeCookies::orderBy('created_at', 'DESC')->get();

        return view('painel.cookies.index', compact('registros'));
    }
}

laravel/app/Http/Controllers/Painel/BannersController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Http\Requests\BannersRequest;
use App\Models\Banner;

class BannersController extends Controller
{
    public function index()
    {
        $banners = Banner::ordenados()->get();

        return view('painel.banners.index', compact('banners'));
    }

    public function create()
    {
        return view('painel.banners.create');
    }

    public function store(BannersRequest $request)
    {
        try {
            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Banner::upload_imagem();

            Banner::create($input);

            return redirect()->route('painel.banners.index')->with('success', 'Registro adicionado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: ' . $e->getMessage()]);
        }
    }

    public function edit(Banner $banner)
    {
        return view('painel.banners.edit', compact('banner'));
    }

    public function update(BannersRequest $request, Banner $banner)
    {
        try {
            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Banner::upload_imagem();

            $banner->update($input);

            return redirect()->route('painel.banners.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: ' . $e->getMessage()]);
        }
    }

    public function destroy(Banner $banner)
    {
        try {
            $banner->delete();

            return redirect()->route('painel.banners.index')->with('success', 'Registro excluído com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: ' . $e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/ConfiguracoesController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Http\Requests\ConfiguracoesRequest;
use App\Models\Configuracao;

class ConfiguracoesController extends Controller
{
    public function index()
    {
        $registro = Configuracao::first();

        return view('painel.configuracoes.edit', compact('registro'));
    }

    public function update(ConfiguracoesRequest $request, Configuracao $registro)
    {
        try {
            $input = $request->all();

            if (isset($input['imagem_de_compartilhamento'])) $input['imagem_de_compartilhamento'] = Configuracao::upload_imagem_de_compartilhamento();

            $registro->update($input);

            return redirect()->route('painel.configuracoes.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: ' . $e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/ContatoController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Http\Requests\ContatoRequest;
use App\Models\Contato;

class ContatoController extends Controller
{
    public function index()
    {
        $contato = Contato::first();

        return view('painel.contato.index', compact('contato'));
    }

    public function update(ContatoRequest $request, Contato $contato)
    {
        try {
            $input = $request->all();

            $contato->update($input);

            return redirect()->route('painel.contato.index')->with('success', 'Informações alteradas com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar informações: ' . $e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/ContatosRecebidosController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Controllers\Controller;
use App\Models\ContatoRecebido;

class ContatosRecebidosController extends Controller
{
    public function index()
    {
        $contatosrecebidos = ContatoRecebido::orderBy('created_at', 'DESC')->get();

        return view('painel.contato.recebidos.index', compact('contatosrecebidos'));
    }

    public function show($contatoRecebido)
    {
        $contato = ContatoRecebido::where('id', $contatoRecebido)->first();
        $contato->update(['lido' => 1]);

        return view('painel.contato.recebidos.show', compact('contato'));
    }

    public function destroy($contatoRecebido)
    {
        try {
            $contato = ContatoRecebido::where('id', $contatoRecebido)->first();
            $contato->delete();

            return redirect()->route('painel.contato.recebidos.index')->with('success', 'Mensagem excluída com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir mensagem: ' . $e->getMessage()]);
        }
    }

    public function toggle($contatoRecebido)
    {
        try {
            $contato = ContatoRecebido::where('id', $contatoRecebido)->first();
            $contato->update([
                'lido' => !$contato->lido
            ]);

            return redirect()->route('painel.contato.recebidos.index')->with('success', 'Mensagem alterada com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar mensagem: ' . $e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/MidiasController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Http\Requests\MidiasRequest;
use App\Models\Midia;
use App\Models\MidiaGaleria;
use App\Models\MidiaTipo;

class MidiasController extends Controller
{
    public function index()
    {
        $tipos = MidiaTipo::orderBy('id', 'ASC')->get();

        $midias = Midia::ordenados()->get();

        $capasLinks = Midia::join('midias_links', 'midias_links.midia_id', '=', 'midias.id')
            ->select('midias_links.midia_id as midia_id', 'midias.tipo_id as tipo_id', 'midias_links.capa as capa')
            ->get();
        $capasGalerias = Midia::join('midias_galerias', 'midias_galerias.midia_id', '=', 'midias.id')
            ->select('midias_galerias.midia_id as midia_id', 'midias.tipo_id as tipo_id', 'midias_galerias.capa as capa')
            ->get();
        $capasVideos = Midia::join('midias_videos', 'midias_videos.midia_id', '=', 'midias.id')
            ->select('midias_videos.midia_id as midia_id', 'midias.tipo_id as tipo_id', 'midias_videos.link_video as link_video')
            ->get();

        return view('painel.midias.index', compact('midias', 'tipos', 'capasGalerias', 'capasLinks', 'capasVideos'));
    }

    public function create()
    {
        $tipos = MidiaTipo::orderBy('id', 'ASC')->pluck('titulo', 'id');

        return view('painel.midias.create', compact('tipos'));
    }

    public function store(MidiasRequest $request)
    {
        try {
            $input = $request->all();
            $input['slug'] = str_slug($request->titulo, '-');

            Midia::create($input);

            return redirect()->route('painel.midias.index')->with('success', 'Registro adicionado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: ' . $e->getMessage()]);
        }
    }

    public function edit(Midia $midia)
    {
        $tipos = MidiaTipo::orderBy('id', 'ASC')->pluck('titulo', 'id');

        return view('painel.midias.edit', compact('midia', 'tipos'));
    }

    public function update(MidiasRequest $request, Midia $midia)
    {
        try {
            $input = $request->all();
            $input['slug'] = str_slug($request->titulo, '-');

            $midia->update($input);

            return redirect()->route('painel.midias.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: ' . $e->getMessage()]);
        }
    }

    public function destroy(Midia $midia)
    {
        try {
            $midia->delete();

            return redirect()->route('painel.midias.index')->with('success', 'Registro excluído com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: ' . $e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/MidiasGaleriasController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Http\Requests\MidiasGaleriasRequest;
use App\Models\Midia;
use App\Models\MidiaGaleria;

class MidiasGaleriasController extends Controller
{
    public function index(Midia $midia)
    {
        $galeria = MidiaGaleria::where('midia_id', $midia->id)->first();

        return view('painel.midias.galeria.index', compact('midia', 'galeria'));
    }

    public function create(Midia $midia)
    {
        return view('painel.midias.galeria.create', compact('midia'));
    }

    public function store(MidiasGaleriasRequest $request, Midia $midia)
    {
        try {
            $input = $request->all();
            $input['midia_id'] = $midia->id;

            if (isset($input['capa'])) $input['capa'] = MidiaGaleria::upload_capa();

            MidiaGaleria::create($input);

            return redirect()->route('painel.midias.galeria.index', $midia->id)->with('success', 'Registro adicionado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: ' . $e->getMessage()]);
        }
    }

    public function edit(Midia $midia, MidiaGaleria $galeria)
    {
        return view('painel.midias.galeria.edit', compact('midia', 'galeria'));
    }

    public function update(MidiasGaleriasRequest $request, Midia $midia, MidiaGaleria $galeria)
    {
        try {
            $input = $request->all();
            $input['midia_id'] = $midia->id;

            if (isset($input['capa'])) $input['capa'] = MidiaGaleria::upload_capa();

            $galeria->update($input);

            return redirect()->route('painel.midias.galeria.index', $midia->id)->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: ' . $e->getMessage()]);
        }
    }

    public function destroy(Midia $midia, MidiaGaleria $galeria)
    {
        try {
            $galeria->delete();

            return redirect()->route('painel.midias.galeria.index', $midia->id)->with('success', 'Registro excluído com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: ' . $e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/PoliticaDePrivacidadeController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Http\Requests\PoliticaDePrivacidadeRequest;
use App\Models\PoliticaDePrivacidade;

class PoliticaDePrivacidadeController extends Controller
{
    public function index()
    {
        $registro = PoliticaDePrivacidade::first();

        return view('painel.politica-de-privacidade.edit', compact('registro'));
    }

    public function update(PoliticaDePrivacidadeRequest $request, PoliticaDePrivacidade $registro)
    {
        try {
            $input = $request->all();

            $registro->update($input);

            return redirect()->route('painel.politica-de-privacidade.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: ' . $e->getMessage()]);
        }
    }
}

laravel/resources/views/painel/projetos-antes-depois/create.blade.php
@extends('painel.common.template')

@section('content')

    <legend>
        <h2><small>Projetos | Antes e Depois |</small> Adicionar Projeto</h2>
    </legend>

    {!! Form::open(['route' => 'painel.projetos-antes-depois.store', 'files' => true]) !!}

        @include('painel.projetos-antes-depois.form', ['submitText' => 'Inserir'])

    {!! Form::close() !!}

@endsection

laravel/resources/views/painel/projetos-antes-depois/edit.blade.php
@extends('painel.common.template')

@section('content')

    <legend>
        <h2><small>Projetos | Antes e Depois |</small> Editar Projeto</h2>
    </legend>

    {!! Form::model($projeto, [
        'route'  => ['painel.projetos-antes-depois.update', $projeto->id],
        'method' => 'patch',
        'files'  => true])
    !!}

    @include('painel.projetos-antes-depois.form', ['submitText' => 'Alterar'])

    {!! Form::close() !!}

@endsection

laravel/resources/views/painel/projetos-antes-depois/form.blade.php
@include('painel.common.flash')

<div class="form-group">
    {!! Form::label('categoria_id', 'Categoria') !!}
    {!! Form::select('categoria_id', $categorias , old('categoria_id'), ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('titulo', 'Título') !!}
    {!! Form::text('titulo', null, ['class' => 'form-control']) !!}
</div>

<div class="well form-group">
    {!! Form::label('capa', 'Capa') !!}
    @if($submitText == 'Alterar')
    <img src="{{ url('assets/img/projetos-antes-depois/'.$projeto->capa) }}" style="display:block; margin-bottom: 10px; max-width: 100%;">
    @endif
    {!! Form::file('capa', ['class' => 'form-control']) !!}
</div>

<div class="well">
    <div class="checkbox" style="margin:0">
        <label style="font-weight:bold">
            {!! Form::hidden('ativo', 0) !!}
            {!! Form::checkbox('ativo') !!}
            Ativo
        </label>
    </div>
</div>

<hr>

{!! Form::submit($submitText, ['class' => 'btn btn-success']) !!}

<a href="{{ route('painel.projetos-antes-depois.index') }}" class="btn btn-default btn-voltar">Voltar</a>

laravel/resources/views/painel/projetos-antes-depois/index.blade.php
@extends('painel.common.template')

@section('content')

@include('painel.common.flash')

<legend>
    <h2>
        Projetos | Antes e Depois
        <a href="{{ route('painel.projetos-antes-depois.create') }}" class="btn btn-success btn-sm pull-right"><span class="glyphicon glyphicon-plus" style="margin-right:10px;"></span>Adicionar Projeto</a>
    </h2>
</legend>

<h4 class="titulo-categorias">Categorias:</h4>
<div class="lista-categorias">
    @foreach($categorias as $categoria)
    <a href="{{ route('painel.projetos-antes-depois.index', ['categoria' => $categoria->id]) }}" class="categoria {{ (isset($_GET['categoria']) && $_GET['categoria'] == $categoria->id) ? 'active' : '' }}">{{ $categoria->titulo }}</a>
    @endforeach
</div>

@if(!count($projetos))
<div class="alert alert-warning" role="alert">Nenhum registro encontrado.</div>
@else
<table class="table table-striped table-bordered table-hover table-info table-sortable" data-table="projetos_antes_depois">
    <thead>
        <tr>
            <th>Ordenar</th>
            <th>Capa</th>
            <th>Título</th>
            <th>Ativo</th>
            <th>Gerenciar</th>
            <th class="no-filter"><span class="glyphicon glyphicon-cog"></span></th>
        </tr>
    </thead>

    <tbody>
        @foreach ($projetos as $projeto)
        <tr class="tr-row" id="{{ $projeto->id }}">
            <td>
                <a href="#" class="btn btn-info btn-sm btn-move">
                    <span class="glyphicon glyphicon-move"></span>
                </a>
            </td>
            <td><img src="{{ asset('assets/img/projetos-antes-depois/'.$projeto->capa) }}" style="width: 100%; max-width:80px;" alt=""></td>
            <td>{{ $projeto->titulo }}</td>
            <td>
                <span class="glyphicon {{ $projeto->ativo ? 'text-success glyphicon-ok' : 'text-danger glyphicon-remove' }}"></span>
            </td>
            <td><a href="{{ route('painel.projetos-antes-depois.imagens.index', $projeto->id) }}" class="btn btn-info btn-sm">
                    <span class="glyphicon glyphicon-picture" style="margin-right:10px;"></span>Imagens
                </a></td>
            <td class="crud-actions">
                {!! Form::open([
                'route' => ['painel.projetos-antes-depois.destroy', $projeto->id],
                'method' => 'delete'
                ]) !!}

                <div class="btn-group btn-group-sm">
                    <a href="{{ route('painel.projetos-antes-depois.edit', $projeto->id ) }}" class="btn btn-primary btn-sm pull-left">
                        <span class="glyphicon glyphicon-pencil" style="margin-right:10px;"></span>Editar
                    </a>

                    <button type="submit" class="btn btn-danger btn-sm btn-delete"><span class="glyphicon glyphicon-remove" style="margin-right:10px;"></span>Excluir</button>
                </div>

                {!! Form::close() !!}
            </td>
        </tr>
        @endforeach
    </tbody>
</table>
@endif

@endsection