laravel/app/Http/routes.php
<?php

use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Route;

Route::group(['middleware' => ['web']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('sobre', 'SobreController@index')->name('sobre');
    Route::get('projetos/antes-e-depois', 'ProjetosController@indexAntesDepois')->name('projetos.antes-depois');
    Route::get('projetos/antes-e-depois/{projeto}', 'ProjetosController@showAntesDepois')->name('projetos.antes-depois.show');
    Route::get('projetos', 'ProjetosController@index')->name('projetos');
    Route::get('projetos/{projeto}', 'ProjetosController@showImagens')->name('projetos.show');
    Route::get('projetos/categoria/{categoria}', 'ProjetosController@showCategoria')->name('projetos.categoria');
    Route::get('projetos/{categoria}/{projeto}', 'ProjetosController@showCategoriaImagens')->name('projetos.categoria.show');
    Route::get('midia', 'MidiaController@index')->name('midia');
    Route::get('contato', 'ContatoController@index')->name('contato');
    Route::post('contato', 'ContatoController@post')->name('contato.post');
    Route::get('politica-de-privacidade', 'PoliticaDePrivacidadeController@index')->name('politica-de-privacidade');
    Route::post('aceite-de-cookies', 'HomeController@postCookies')->name('aceite-de-cookies.post');

    // Painel
    Route::group([
        'prefix'     => 'painel',
        'namespace'  => 'Painel',
        'middleware' => ['auth']
    ], function () {
        Route::get('/', 'PainelController@index')->name('painel');
        Route::post('ckeditor-upload', 'PainelController@imageUpload');
        Route::post('order', 'PainelController@order');
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
        Route::resource('banners', 'BannersController');
        Route::resource('sobre', 'SobreController', ['only' => ['index', 'update']]);
        Route::resource('projetos', 'ProjetosController', ['except' => 'show']);
        Route::get('projetos/{projeto}/imagens/clear', [
            'as'   => 'painel.projetos.imagens.clear',
            'uses' => 'ProjetosImagensController@clear'
        ]);
        Route::delete('projetos/{projeto}/excluir-imagens/{imagens}', 'ProjetosImagensController@destroyImgs')->name('painel.projetos.excluir-imagens');
        Route::post('projetos/{projeto}/imagens/{imagem}/descricao', 'ProjetosImagensController@updateDescricao')->name('painel.projetos.imagens.descricao');
        Route::resource('projetos.imagens', 'ProjetosImagensController', ['parameters' => ['imagens' => 'projetos_imagens']]);
        Route::resource('projetos-antes-depois', 'ProjetosAntesDepoisController', ['except' => 'show']);
        Route::resource('projetos-antes-depois.imagens', 'ProjetosAntesDepoisImagensController');
        Route::resource('midias', 'MidiasController');
        Route::resource('midias.galeria', 'MidiasGaleriasController');
        Route::get('midias/{galeria}/imagens/clear', [
            'as'   => 'painel.midias.galeria.imagens.clear',
            'uses' => 'MidiasGaleriasImagensController@clear'
        ]);
        Route::resource('midias.galeria.imagens', 'MidiasGaleriasImagensController', ['parameters' => ['imagens' => 'midias_galerias_imagens']]);
        Route::resource('midias.link', 'MidiasLinksController');
        Route::resource('midias.video', 'MidiasVideosController');
        Route::get('contato/recebidos/{recebidos}/toggle', ['as' => 'painel.contato.recebidos.toggle', 'uses' => 'ContatosRecebidosController@toggle']);
        Route::resource('contato/recebidos', 'ContatosRecebidosController');
        Route::resource('contato', 'ContatoController');
        Route::resource('politica-de-privacidade', 'PoliticaDePrivacidadeController', ['only' => ['index', 'update']]);
        Route::get('aceite-de-cookies', 'AceiteDeCookiesController@index')->name('painel.aceite-de-cookies');
        Route::resource('configuracoes', 'ConfiguracoesController', ['only' => ['index', 'update']]);
        Route::resource('usuarios', 'UsuariosController');

        // Limpar caches
        Route::get('clear-cache', function() {
            $exitCode = Artisan::call('config:clear');
            $exitCode = Artisan::call('cache:clear');
            $exitCode = Artisan::call('route:clear');
            $exitCode = Artisan::call('view:clear');
            $exitCode = Artisan::call('config:cache');

            return 'DONE';
        });
    });

    // Auth
    Route::group([
        'prefix'    => 'painel',
        'namespace' => 'Auth'
    ], function () {
        Route::get('login', 'AuthController@showLoginForm')->name('auth');
        Route::post('login', 'AuthController@login')->name('login');
        Route::get('logout', 'AuthController@logout')->name('logout');
        Route::get('esqueci-minha-senha', 'PasswordController@sendEmail')->name('esqueci-minha-senha');
        Route::post('esqueci-minha-senha', 'PasswordController@sendResetLinkEmail')->name('esqueci-minha-senha.post');
        Route::get('reset/{token}', 'PasswordController@showResetForm')->name('password-reset');
        Route::post('reset', 'PasswordController@reset')->name('password-reset.post');
    });
});

laravel/app/Models/Midia.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Midia extends Model
{
    protected $table = 'midias';

    protected $guarded = ['id'];

    public function scopeOrdenados($query)
    {
        return $query->orderBy('ordem', 'ASC')->orderBy('id', 'DESC');
    }

    public function scopeTipos($query, $id)
    {
        return $query->where('tipo_id', $id);
    }
}

laravel/app/Http/Controllers/MidiaController.php
<?php

namespace App\Http\Controllers;

use App\Models\Midia;
use App\Models\MidiaGaleria;
use App\Models\MidiaLink;
use App\Models\MidiaVideo;

class MidiaController extends Controller
{
    public function index()
    {
        $midias = Midia::ordenados()
            ->join('midias_tipos', 'midias_tipos.id', '=', 'midias.tipo_id')
            ->select('midias_tipos.id as tipo_id', 'midias_tipos.titulo as tipo_titulo', 'midias.id as id', 'midias.ordem as ordem', 'midias.slug as slug', 'midias.titulo as titulo', 'midias.ano as ano')
            ->get();

        $galerias = MidiaGaleria::get();
        $links = MidiaLink::get();
        $videos = MidiaVideo::get();

        return view('frontend.midia', compact('midias', 'galerias', 'links', 'videos'));
    }
}

laravel/app/Http/Controllers/Painel/MidiasController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Http\Requests\MidiasRequest;
use App\Models\Midia;
use App\Models\MidiaGaleria;
use App\Models\MidiaTipo;

class MidiasController extends Controller
{
    public function index()
    {
        $tipos = MidiaTipo::orderBy('id', 'ASC')->get();

        $midias = Midia::ordenados()->get();

        $capasLinks = Midia::join('midias_links', 'midias_links.midia_id', '=', 'midias.id')
            ->select('midias_links.midia_id as midia_id', 'midias.tipo_id as tipo_id', 'midias_links.capa as capa')
            ->get();
        $capasGalerias = Midia::join('midias_galerias', 'midias_galerias.midia_id', '=', 'midias.id')
            ->select('midias_galerias.midia_id as midia_id', 'midias.tipo_id as tipo_id', 'midias_galerias.capa as capa')
            ->get();
        $capasVideos = Midia::join('midias_videos', 'midias_videos.midia_id', '=', 'midias.id')
            ->select('midias_videos.midia_id as midia_id', 'midias.tipo_id as tipo_id', 'midias_videos.link_video as link_video')
            ->get();

        return view('painel.midias.index', compact('midias', 'tipos', 'capasGalerias', 'capasLinks', 'capasVideos'));
    }

    public function create()
    {
        $tipos = MidiaTipo::orderBy('id', 'ASC')->pluck('titulo', 'id');

        return view('painel.midias.create', compact('tipos'));
    }

    public function store(MidiasRequest $request)
    {
        try {
            $input = $request->all();
            $input['slug'] = str_slug($request->titulo, '-');

            Midia::create($input);

            return redirect()->route('painel.midias.index')->with('success', 'Registro adicionado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: ' . $e->getMessage()]);
        }
    }

    public function edit(Midia $midia)
    {
        $tipos = MidiaTipo::orderBy('id', 'ASC')->pluck('titulo', 'id');

        return view('painel.midias.edit', compact('midia', 'tipos'));
    }

    public function update(MidiasRequest $request, Midia $midia)
    {
        try {
            $input = $request->all();
            $input['slug'] = str_slug($request->titulo, '-');

            $midia->update($input);

            return redirect()->route('painel.midias.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: ' . $e->getMessage()]);
        }
    }

    public function destroy(Midia $midia)
    {
        try {
            $midia->delete();

            return redirect()->route('painel.midias.index')->with('success', 'Registro excluído com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: ' . $e->getMessage()]);
        }
    }
}

laravel/resources/views/painel/midias/video/create.blade.php
@extends('painel.common.template')

@section('content')

<legend>
    <h2><small>Mídia | Vídeo (YouTube) |</small> Adicionar Vídeo</h2>
</legend>

{!! Form::model($midia, [
'route' => ['painel.midias.video.store', $midia->id],
'method' => 'post',
'files' => true])
!!}

@include('painel.midias.video.form', ['submitText' => 'Inserir'])

{!! Form::close() !!}

@endsection

laravel/resources/views/painel/midias/video/edit.blade.php
@extends('painel.common.template')

@section('content')

<legend>
    <h2><small>Mídia | Vídeo (YouTube) |</small> Editar Vídeo</h2>
</legend>

{!! Form::model($video, [
'route' => ['painel.midias.video.update', $midia->id, $video->id],
'method' => 'patch',
'files' => true])
!!}

@include('painel.midias.video.form', ['submitText' => 'Alterar'])

{!! Form::close() !!}

@endsection

laravel/resources/views/painel/midias/video/form.blade.php
@include('painel.common.flash')

<div class="form-group">
    {!! Form::label('link_video', 'Vídeo do YouTube') !!}
    {!! Form::text('link_video', null, ['class' => 'form-control']) !!}
    <p class="observacao" style="color: red; font-style: italic;">Incluir aqui somente a parte da url após o "v=". Exemplo: <span style="text-decoration: underline;">https://www.youtube.com/watch?v=<strong>Y4goaZhNt4k</strong></span></p>
</div>

<hr>

{!! Form::submit($submitText, ['class' => 'btn btn-success']) !!}

<a href="{{ route('painel.midias.video.index', $midia->id) }}" class="btn btn-default btn-voltar">Voltar</a>

laravel/resources/views/painel/midias/video/index.blade.php
@extends('painel.common.template')

@section('content')

@include('painel.common.flash')

<legend>
    <h2>
        Mídia | Vídeo (YouTube)
    </h2>
    <a href="{{ route('painel.midias.index') }}" title="Voltar para Mídias" class="btn btn-sm btn-default">
        &larr; Voltar para Mídias</a>
</legend>

@if($video == null)
<div class="alert alert-warning" role="alert" style="display: flex; justify-content: space-between; align-items: center;">Nenhum registro encontrado.
    <a href="{{ route('painel.midias.video.create', $midia->id) }}" class="btn btn-success btn-sm pull-right"><span class="glyphicon glyphicon-plus" style="margin-right:10px;"></span>Adicionar Vídeo (YouTube)</a>
</div>

@else
<table class="table table-striped table-bordered table-hover table-info table-sortable" data-table="midias_videos">
    <thead>
        <tr>
            <th>Título</th>
            <th>Link Vídeo YouTube</th>
            <th class="no-filter"><span class="glyphicon glyphicon-cog"></span></th>
        </tr>
    </thead>

    <tbody>
        <tr class="tr-row" id="{{ $video->id }}">
            <td>{{ $midia->titulo }}</td>
            <td>{{ $video->link_video }}</td>
            <td class="crud-actions">
                {!! Form::open([
                'route' => ['painel.midias.video.destroy', $midia->id, $video->id],
                'method' => 'delete'
                ]) !!}

                <div class="btn-group btn-group-sm">
                    <a href="{{ route('painel.midias.video.edit', [$midia->id, $video->id] ) }}" class="btn btn-primary btn-sm pull-left">
                        <span class="glyphicon glyphicon-pencil" style="margin-right:10px;"></span>Editar
                    </a>

                    <button type="submit" class="btn btn-danger btn-sm btn-delete"><span class="glyphicon glyphicon-remove" style="margin-right:10px;"></span>Excluir</button>
                </div>

                {!! Form::close() !!}
            </td>
        </tr>
    </tbody>
</table>
@endif

@endsection